[build]
  publish = "public"
  command = "yarn build"
[build.environment]
  YARN_VERSION = "1.3.2"
  YARN_FLAGS = "--no-ignore-optional"
[[plugins]]
  package = "netlify-plugin-is-website-vulnerable"
[[plugins]]
  package = "netlify-purge-cloudflare-on-deploy"
